SET LINESIZE 200
SET PAGESIZE 200

PROMPT == 0. 환경
SELECT * FROM v$version WHERE name IN ('PRODUCT_MAJOR', 'PRODUCT_MINOR');

PROMPT == 1. 예제 표 — 빈 스키마에 만들고 끝에 지운다
CREATE TABLE xp_emp (
    emp_id    NUMBER PRIMARY KEY,
    dept_id   NUMBER NOT NULL,
    emp_name  VARCHAR(30) NOT NULL
);
CREATE INDEX ix_xp_emp_dept_id ON xp_emp (dept_id);
INSERT INTO xp_emp SELECT LEVEL, MOD(LEVEL, 50), 'emp' || LEVEL FROM dual CONNECT BY LEVEL <= 5000;
COMMIT;
EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'XP_EMP');
DESC xp_emp
SELECT * FROM xp_emp WHERE emp_id <= 5;

PROMPT == 2. PLAN_TABLE 이 있는가 — EXPLAIN PLAN 의 기본 저장 대상
SELECT owner, object_name, object_type FROM all_objects WHERE object_name = 'PLAN_TABLE';

PROMPT == 3. EXPLAIN PLAN + DISPLAY — 기본 형식(BASIC LAST SQL)
EXPLAIN PLAN FOR SELECT emp_name FROM xp_emp WHERE dept_id = 7;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

PROMPT == 4. DISPLAY('ALL') — PREDICATE·OUTLINE 이 붙는가
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('ALL'));

PROMPT == 5. EXPLAIN PLAN 은 자동 커밋하지 않는다 — ROLLBACK 뒤 PLAN_TABLE 행 수
EXPLAIN PLAN SET STATEMENT_ID = 'xp_rb' FOR SELECT * FROM xp_emp WHERE emp_id = 1;
SELECT COUNT(*) AS before_rollback FROM plan_table WHERE statement_id = 'xp_rb';
ROLLBACK;
SELECT COUNT(*) AS after_rollback FROM plan_table WHERE statement_id = 'xp_rb';

PROMPT == 6. 수행 후 DISPLAY_CURSOR — GATHER_SQL_PLAN_STAT 기본값(N)
SELECT COUNT(*) AS cnt FROM xp_emp WHERE dept_id = 7;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'TYPICAL'));

PROMPT == 7. GATHER_SQL_PLAN_STAT = Y 로 켜고 다시 — Rows 가 0 에서 바뀌는가
ALTER SESSION SET GATHER_SQL_PLAN_STAT = Y;
SELECT COUNT(*) AS cnt FROM xp_emp WHERE dept_id = 7;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'TYPICAL'));

PROMPT == 8. 형식 가감 — -COST, +OUTLINE, 틀린 항목 이름
SELECT COUNT(*) AS cnt FROM xp_emp WHERE dept_id = 7;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'TYPICAL -COST +OUTLINE'));
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'TYPICAL +NOSUCH'));

PROMPT == 9. AUTOTRACE — TRACEONLY EXPLAIN / PLANSTAT
SET AUTOTRACE TRACEONLY EXPLAIN
SELECT emp_name FROM xp_emp WHERE dept_id = 7;
SET AUTOTRACE TRACEONLY PLANSTAT
SELECT emp_name FROM xp_emp WHERE dept_id = 7;
SET AUTOTRACE OFF

PROMPT == 10. 정리 — 객체 0개로 되돌린다
DELETE FROM plan_table WHERE statement_id = 'xp_rb';
COMMIT;
DROP TABLE xp_emp PURGE;
SELECT COUNT(*) AS obj_count FROM user_objects;
EXIT
